![image](https://media.geeksforgeeks.org/wp-content/uploads/20250222144920592095/stat.webp)

### Descriptive statistics

In [ ]:
import pandas as pd
import numpy as np
import warnings
import os

In [ ]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats'

In [ ]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='ERPData')

In [10]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [13]:
df.describe()

         Quantity
count   50.000000
mean    57.700000
std     31.887078
min     10.000000
25%     34.000000
50%     54.500000
75%     74.000000
max    152.000000

In [14]:
np.unique(df.MaterialID)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [15]:
len(np.unique(df.MaterialID))

6

In [16]:
len(df.MaterialID)

50

In [17]:
np.unique(df.MaterialID, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [42]:
mat_count = df.MaterialID.value_counts().reset_index()

In [59]:
mat_count

  MaterialID  count  prop
0    TMI-43T     15  30.0
1    AXCP-78     11  22.0
2    DDBN-89      8  16.0
3    SDRT-67      6  12.0
4    LXCV-21      5  10.0
5    GCVB-79      5  10.0

In [58]:
mat_count['prop'] = mat_count['count']/sum(mat_count['count'])*100

# This calculates the percentage (proportion) of each MaterialID's count out of the total count,
# and stores it in a new column 'prop'. Each value shows what percent of the total each MaterialID represents.

In [46]:
mat_count

  MaterialID  count  prop
0    TMI-43T     15  30.0
1    AXCP-78     11  22.0
2    DDBN-89      8  16.0
3    SDRT-67      6  12.0
4    LXCV-21      5  10.0
5    GCVB-79      5  10.0

In [48]:
grades = np.array(['A','B','C'])

In [49]:
grades

array(['A', 'B', 'C'], dtype='<U1')

In [78]:
df = pd.read_excel('data/covid_cases.xlsx')

In [79]:
df.head()

  State  Cases
0    UP    250
1    KA    350
2    MH    650
3    KL    400
4    MP    350

In [80]:
df = df.sort_values('Cases', ascending=False)

In [81]:
df.head()

  State  Cases
2    MH    650
3    KL    400
1    KA    350
4    MP    350
0    UP    250

In [86]:
df['prop'] = df ['Cases']/sum(df['Cases'])*100

In [87]:
df.head()

  State  Cases       prop
2    MH    650  27.083333
3    KL    400  16.666667
1    KA    350  14.583333
4    MP    350  14.583333
0    UP    250  10.416667

In [89]:
round(np.cumsum(df.prop),2)

2     27.08
3     43.75
1     58.33
4     72.92
0     83.33
5     89.58
7     95.83
6    100.00
Name: prop, dtype: float64

In [90]:
np.cumsum(df.prop).iloc[1]

np.float64(43.75)

In [ ]:
# central tendancy - mean , median and mode
# variation or dispersion - range, inter quartile range, variance, std deviation
# shape - skewness and kurtosis



# if n is odd then n+1/2 for median, otherwise there are two values then take the average of those two middle values, so n/2 + (n/2)+!

# example 

# 5,8,2,3,9 -> 2,3,5,8,9    (after sorting) so middle is 5, which is median

# 2,3,5,8,9,10              so  (5+8)/2 = 6.5 median

In [ ]:
# mean of 20 values found to be 10
# one of the values which was actually 60 was writtin as 20

In [189]:
grades=np.array(['A','B','C','B','C','A','A','A','B','C','A','A','A','B'])

In [190]:
np.unique(grades,return_counts=True)

(array(['A', 'B', 'C'], dtype='<U1'), array([7, 4, 3]))

In [192]:
p1=np.array([8,3,3])

In [193]:
np.cumsum(p1)     # sum of previous number and number itselt

array([ 8, 11, 14])

In [191]:
np.unique(grades,return_counts=True)[1]

array([7, 4, 3])

In [92]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='faithful')

In [93]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [95]:
erupt = df['eruptions']

In [96]:
len(erupt)

272

In [97]:
sum(erupt)

948.677

In [101]:
m = sum(erupt)/len(erupt)

In [102]:
m

3.487783088235294

In [103]:
np.mean(erupt)

np.float64(3.4877830882352936)

In [105]:
df.eruptions.mean()

np.float64(3.4877830882352936)

In [106]:
x1 = np.sort(erupt)

In [108]:
x1[135]

np.float64(4.0)

In [109]:
x1[136]

np.float64(4.0)

In [110]:
(x1[135] + x1[136])/2

np.float64(4.0)

In [111]:
np.median(erupt)

np.float64(4.0)

In [ ]:
students = [20,35,15]
total_marks = [8,9,10]

In [112]:
nums = np.array([20,35,15])
marks = np.array([8,9,10])

In [113]:
sum(nums*marks)/sum(nums)

np.float64(8.928571428571429)

In [118]:
len(np.where(erupt==1.867)[0])

8

In [125]:
np.where(erupt==1.867)

(array([ 36,  92,  98, 105, 130, 203, 212, 220]),)

In [ ]:
# don't calcualate mean if the values are highly volatile, calculate median instead
# median can be calculated at any situation
# calculation graphs should prefer higher number of records like salary [1,2,3,4,3,1,2,90,91] -> so the graph should be favoring the less salary people in viz.

# mode = most frequent element
# per dataset there could be only 1 mean and 1 median, but modes could be more (bimodal, multimodal)

In [126]:
np.ptp(erupt)                                       # calculate range inbuild

np.float64(3.4999999999999996)

In [128]:
max(erupt)-min(erupt)                               # calculate range manual


# note - range shouldn't be used if the dataset is with extreme values

3.4999999999999996

In [159]:
# there should be consistency while using the range, lots of organizations have stopped using the range

x1 = [4,5,6,3,4,2,3,4,4,5,1,9] # -> range is 8
x2 = [6,6,6,6,6,6,6,6,6,6,1,9] # -> range is 8 


# here in both cases the range is 8 but the x2 is more consistent

In [131]:
np.percentile(erupt,40)

np.float64(3.6)

In [133]:
np.percentile(erupt,40)
np.percentile(erupt,80)

np.float64(4.533)

In [135]:
max(erupt)

5.1

#### manual vs inbuilt method to calculate percentile, and understand percentile

In [142]:
t1=[1,1,2,2,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,7]

In [143]:
1 + (len(t1)-1) * 0.25

8.25

In [144]:
3 * 0.25 + 4 * 0.75

3.75

In [145]:
np.percentile(t1,25)

np.float64(3.25)

In [146]:
3 * 0.75 + 4* 0.25

3.25

In [147]:
1 + (len(t1)-1) * 0.7

21.299999999999997

In [148]:
t1[20]

6

In [149]:
t1[21]

6

In [150]:
1 + (len(t1) + 1) * 0.8

25.8

In [151]:
t1[23]

6

In [152]:
t1[24]

7

In [153]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [154]:
df.describe()

        eruptions     waiting
count  272.000000  272.000000
mean     3.487783   70.897059
std      1.141371   13.594974
min      1.600000   43.000000
25%      2.162750   58.000000
50%      4.000000   76.000000
75%      4.454250   82.000000
max      5.100000   96.000000

In [156]:
np.percentile(erupt, 75) - np.percentile(erupt, 25)

np.float64(2.2915)

In [160]:
np.percentile(x2, 75) - np.percentile(x2, 25)

np.float64(0.0)

In [161]:
x2

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 9]

In [162]:
np.var(erupt)        #population variance

np.float64(1.2979388904492861)

In [163]:
np.var(erupt, ddof=1)    # sample variance

np.float64(1.302728332849468)

In [164]:
np.std(erupt)             # population standard variance

np.float64(1.139271210225768)

In [165]:
np.std(erupt, ddof=1)      # sample standard deviation

np.float64(1.141371251105208)

In [166]:
len(erupt - np.mean(erupt))

272

In [167]:
sum(erupt - np.mean(erupt))

1.4854784069484595e-13

In [171]:
ss = sum((erupt - np.mean(erupt))**2)  # sum of squared deviation from mean

In [172]:
ss/len(erupt)

1.2979388904492863

In [173]:
np.var(erupt)

np.float64(1.2979388904492861)

In [174]:
(ss/len(erupt) ** 0.5)

21.406156563677587

In [175]:
np.std(erupt)

np.float64(1.139271210225768)

In [176]:
ss/(len(erupt)-1)

1.3027283328494683

In [177]:
np.var(erupt, ddof=1)

np.float64(1.302728332849468)

In [ ]:
ss/(len(erupt)-1) ** 0.5

In [ ]:
#  same task repeated under similar condition is normal distribution
# for eg - going home on the same time, but sometimes it get late

In [179]:
import scipy

In [181]:
from scipy import stats

In [ ]:
scipy.stats.skew(erupt)


# 1. no skewness = 0
# 2. positive skewness > 0
# 3. negative skewness < 0

np.float64(-0.4158409529189896)

![skewn](https://media.geeksforgeeks.org/wp-content/uploads/20231101173636/Skewness-copy.webp)

In [187]:
scipy.stats.kurtosis(erupt)

np.float64(-1.5006003587752426)