In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings

In [ ]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [50]:
df = pd.read_csv('data/Delivery_Food.csv')
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [51]:
# Order_ID              – Unique identifier for each order.
# Distance_km           – Distance between the restaurant and the customer.
# Weather               – Weather conditions at the time of delivery.
# Traffic_Level         – Traffic conditions during the delivery.
# Time_of_Day           – Time interval when the order was placed (Morning/Afternoon/Evening/Night).
# Vehicle_Type          – Type of vehicle used by the delivery person.
# Preparation_Time_min  – Time taken by the restaurant to prepare the food after receiving the order.
# Courier_Exp_yrs       – Delivery person’s experience (in years).
# Delivery_Time_min     – Total time taken to deliver the order.

In [52]:
df.isna().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [53]:
df.shape

(1000, 9)

In [54]:
df.dtypes

Order_ID                    int64
Distance_km               float64
Weather                    object
Traffic_Level              object
Time_of_Day                object
Vehicle_Type               object
Preparation_Time_min        int64
Courier_Experience_yrs    float64
Delivery_Time_min           int64
dtype: object

In [55]:
(df.Weather.value_counts())

Weather
Clear    470
Rainy    204
Foggy    103
Snowy     97
Windy     96
Name: count, dtype: int64

In [56]:
df.isnull().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [57]:
df.Traffic_Level = df.Traffic_Level.fillna(df.Traffic_Level.mode()[0])
df.Weather = df.Weather.fillna(df.Weather.mode()[0])
df.Time_of_Day = df.Time_of_Day.fillna(df.Time_of_Day.mode()[0])
df.Courier_Experience_yrs = df.Courier_Experience_yrs.fillna(df.Courier_Experience_yrs.median())

In [58]:
df.isnull().sum()

Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64

In [59]:
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [65]:
num_cols = ['Order_ID','Distance_km','Preparation_Time_min','Delivery_Time_min']
num_df = df[num_cols]

In [72]:
categorical_view = ['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type']
cat_df = df[categorical_view]

In [73]:
cat_df.head()

  Weather Traffic_Level Time_of_Day Vehicle_Type
0   Windy           Low   Afternoon      Scooter
1   Clear        Medium     Evening         Bike
2   Foggy           Low       Night      Scooter
3   Rainy        Medium   Afternoon      Scooter
4   Clear           Low     Morning         Bike

In [74]:
tar = df.Delivery_Time_min

In [82]:
df = df.drop(columns = 'Order_ID')

In [83]:
df.head()

,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [84]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop('Delivery_Time_min', axis = 1)       # dropped target var, now x = what model sees to learn how to predict target
y = df['Delivery_Time_min']                      # target variable

In [87]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=20)

In [88]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
preprocessor = ColumnTransformer(transformer = [('ohe', OneHotEncoder(handle_unknown='ignore', drop = None))])

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(handle_unknown='ignore', drop=None), cat_cols)
    ],
    remainder='passthrough'   # keep numerical columns
)